apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackoverp20kcabdev-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stackoverp20kcabdev
  template:
    metadata:
      labels:
        app: stackoverp20kcabdev
    spec:
      containers:
      - name: stackoverp20kcabdev
        image: psykali/stackoverp20kcabdev:latest
        ports:
        - containerPort: 80
