apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackoverp20kcab-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stackoverp20kcab
  template:
    metadata:
      labels:
        app: stackoverp20kcab
    spec:
      containers:
      - name: stackoverp20kcab
        image: psykali/stackoverp20kcab:latest
        ports:
        - containerPort: 80
