# Define the Kubernetes deployment for sof-p20
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sof-p20
  namespace: sof-p20
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sof-p20
  template:
    metadata:
      labels:
        app: sof-p20
    spec:
      containers:
      - name: sof-p20
        image: psykali/stackoverp20kcab:latest
        ports:
        - containerPort: 80

# Define the Kubernetes service for sof-p20
apiVersion: v1
kind: Service
metadata:
  name: sof-p20
  namespace: sof-p20
spec:
  selector:
    app: sof-p20
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

---

# Define the Kubernetes deployment for wp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  namespace: wp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wordpress/wordpress:latest
        ports:
        - containerPort: 80

# Define the Kubernetes service for wp
apiVersion: v1
kind: Service
metadata:
  name: wp
  namespace: wp
spec:
  selector:
    app: wp
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer