# azure-pipeline.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    command: 'build'
    repository: 'psykali/stackoverp20kcab'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: 'latest'

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    command: 'push'
    repository: 'psykali/stackoverp20kcab'
    tags: 'latest'