trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install -y sshpass

- task: Bash@3
  inputs:
    filePath: 'rocket-chat-install.sh'